package thejosh.us.StarWarsQuotesAPI.controllers;

import thejosh.us.StarWarsQuotesAPI.model.Quote;
import thejosh.us.StarWarsQuotesAPI.repository.QuoteRepository;

public class QuoteBuilder {
    private final QuoteRepository repository;

    public QuoteBuilder(QuoteRepository repository){
        this.repository =repository;
    }

    public void generateDB(){

        // Save some quotes
        repository.save(new Quote("May the Force be with you.","Various","A New Hope"));
        repository.save(new Quote("I find your lack of faith disturbing.","Darth Vader","A New Hope"));
        repository.save(new Quote("Do. Or do not. There is no try.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("The Force will be with you, always.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("It's a trap!","Admiral Ackbar","Return of the Jedi"));
        repository.save(new Quote("Help me, Obi-Wan Kenobi. You're my only hope.","Princess Leia","A New Hope"));
        repository.save(new Quote("I am your father.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("I've got a bad feeling about this.","Various","Various"));
        repository.save(new Quote("Never tell me the odds.","Han Solo","The Empire Strikes Back"));
        repository.save(new Quote("Fear is the path to the dark side. Fear leads to anger, anger leads to hate, hate leads to suffering.","Yoda","The Phantom Menace"));
        repository.save(new Quote("You were the chosen one! It was said that you would destroy the Sith, not join them! Bring balance to the Force, not leave it in darkness!","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("That's no moon. It's a space station.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I'll never turn to the dark side. You've failed, your highness. I am a Jedi, like my father before me.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("Laugh it up, fuzzball.","Han Solo","The Empire Strikes Back"));
        repository.save(new Quote("Your eyes can deceive you. Don't trust them.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("You must unlearn what you have learned.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Size matters not. Look at me. Judge me by my size, do you?","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("If there's a bright center to the universe, you're on the planet that it's farthest from.","Luke Skywalker","A New Hope"));
        repository.save(new Quote("I'm one with the Force. The Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("Aren't you a little short for a stormtrooper?","Leia Organa","A New Hope"));
        repository.save(new Quote("Rebellions are built on hope.","Jyn Erso","Rogue One"));
        repository.save(new Quote("You don't know how hard I found it, signing the order to terminate your life.","Governor Tarkin","A New Hope"));
        repository.save(new Quote("I don't like sand. It's coarse and rough and irritating and it gets everywhere.","Anakin Skywalker","Attack of the Clones"));
        repository.save(new Quote("That boy is our last hope.","Obi-Wan Kenobi","The Empire Strikes Back"));
        repository.save(new Quote("No. There is another.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("I'm sorry, Dave. I'm afraid I can't do that.","HAL 9000","2001: A Space Odyssey (parody)"));
        repository.save(new Quote("You were right about one thing, Master. The negotiations were short.","Obi-Wan Kenobi","The Phantom Menace"));
        repository.save(new Quote("I sense great fear in you, Skywalker. You have hate. You have anger. But you don't use them.","Count Dooku","Attack of the Clones"));
        repository.save(new Quote("The ability to destroy a planet is insignificant next to the power of the Force.","Darth Vader","A New Hope"));
        repository.save(new Quote("I don't need luck, I have you.","Finn","The Force Awakens"));
        repository.save(new Quote("Chewie, we're home.","Han Solo","The Force Awakens"));
        repository.save(new Quote("I'm a Jedi, like my father before me.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("General Grievous, you're shorter than I expected.","Anakin Skywalker","Revenge of the Sith"));
        repository.save(new Quote("You underestimate the power of the Dark Side.","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("I have brought peace to the Republic. I am more powerful than ever.","Count Dooku","Revenge of the Sith"));
        repository.save(new Quote("I sense a disturbance in the Force.","Obi-Wan Kenobi","The Phantom Menace"));
        repository.save(new Quote("This is a rebellion, isn't it? I rebel.","Jyn Erso","Rogue One"));
        repository.save(new Quote("Truly wonderful, the mind of a child is.","Yoda","Attack of the Clones"));
        repository.save(new Quote("Difficult to see. Always in motion is the future.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Remember, the Force will be with you always.","Obi-Wan Kenobi","Various"));
        repository.save(new Quote("I am one with the Force, and the Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("The Force is strong with this one.","Darth Vader","A New Hope"));
        repository.save(new Quote("I'm standing by as you requested, although there's a problem on the horizon. There's no horizon.","K-2SO","Rogue One"));
        repository.save(new Quote("Let the past die. Kill it, if you have to. That's the only way to become what you were meant to be.","Kylo Ren","The Last Jedi"));
        repository.save(new Quote("A Jedi uses the Force for knowledge and defense, never for attack.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("I am the Senate!","Chancellor Palpatine","Revenge of the Sith"));
        repository.save(new Quote("It's treason, then.","Mace Windu","Revenge of the Sith"));
        repository.save(new Quote("You can't stop change any more than you can stop the suns from setting.","Shmi Skywalker","Attack of the Clones"));
        repository.save(new Quote("The Force is not a power you have. It's not about lifting rocks. It's the energy between all things, a tension, a balance, that binds the universe together.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("No. Try not. Do, or do not. There is no try.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Powerful you have become, the dark side I sense in you.","Yoda","Return of the Jedi"));
        repository.save(new Quote("I have waited a long time for this moment, my little green friend.","Emperor Palpatine","Return of the Jedi"));
        repository.save(new Quote("Let go of your hate.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("You will never find a more wretched hive of scum and villainy.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Twice the pride, double the fall.","Count Dooku","Attack of the Clones"));
        repository.save(new Quote("It's a trap!","Admiral Ackbar","Return of the Jedi"));
        repository.save(new Quote("Impressive... most impressive.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("Good. Use your aggressive feelings, boy. Let the hate flow through you.","Emperor Palpatine","Return of the Jedi"));
        repository.save(new Quote("He will join us or die, my master.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("The dark side clouds everything. Impossible to see the future is.","Yoda","The Phantom Menace"));
        repository.save(new Quote("So this is how liberty dies... with thunderous applause.","Padme Amidala","Revenge of the Sith"));
        repository.save(new Quote("Remember, concentrate on the moment. Feel, don't think. Trust your instincts.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Ah, the negotiator has arrived.","Count Dooku","Attack of the Clones"));
        repository.save(new Quote("Always in motion is the future.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("This party's over.","Mace Windu","Attack of the Clones"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("Hello there.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("Why, you stuck up, half-witted, scruffy-looking Nerf herder!","Leia Organa","The Empire Strikes Back"));
        repository.save(new Quote("Your focus determines your reality.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("The boy you trained, gone he is, consumed by Darth Vader.","Yoda","Return of the Jedi"));
        repository.save(new Quote("I find your lack of faith disturbing.","Darth Vader","A New Hope"));
        repository.save(new Quote("The ability to speak does not make you intelligent.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Do or do not. There is no try.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Into the garbage chute, flyboy!","Leia Organa","A New Hope"));
        repository.save(new Quote("Aren't you a little short for a stormtrooper?","Leia Organa","A New Hope"));
        repository.save(new Quote("Size matters not. Judge me by my size, do you?","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Anakin, you're breaking my heart.","Padme Amidala","Revenge of the Sith"));
        repository.save(new Quote("This is where the fun begins.","Anakin Skywalker","Revenge of the Sith"));
        repository.save(new Quote("I'm one with the Force. The Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("Rebel scum.","Various","Various"));
        repository.save(new Quote("I've got a bad feeling about this.","Various","Various"));
        repository.save(new Quote("We're doomed.","C-3PO","A New Hope"));
        repository.save(new Quote("Use the Force, Luke.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I've been waiting for this moment for a long time.","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("Only a Sith deals in absolutes.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("Great shot, kid. That was one in a million.","Han Solo","A New Hope"));
        repository.save(new Quote("Your overconfidence is your weakness.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("I sense much fear in you.","Yoda","Attack of the Clones"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("You are unwise to lower your defenses!","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("Be mindful of your thoughts, Anakin. They'll betray you.","Obi-Wan Kenobi","Attack of the Clones"));
        repository.save(new Quote("Blast it, Biggs, where are you?","Luke Skywalker","A New Hope"));
        repository.save(new Quote("I will not let you give up your future for me.","Padme Amidala","Revenge of the Sith"));
        repository.save(new Quote("He's holding a thermal detonator!","C-3PO","Return of the Jedi"));
        repository.save(new Quote("Impressive... most impressive.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("We seem to be made to suffer. It's our lot in life.","C-3PO","A New Hope"));
        repository.save(new Quote("I don't like sand. It's coarse and rough and irritating, and it gets everywhere.","Anakin Skywalker","Attack of the Clones"));
        repository.save(new Quote("May the Force be with you.","Various","Various"));
        repository.save(new Quote("Jedi business. Go back to your drinks.","Obi-Wan Kenobi","Attack of the Clones"));
        repository.save(new Quote("Let's just say we'd like to avoid any Imperial entanglements.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Luke, I am your father.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("That's not how the Force works!","Han Solo","The Force Awakens"));
        repository.save(new Quote("I find that answer vague and unconvincing.","K-2SO","Rogue One"));
        repository.save(new Quote("I'm not afraid.","Rey","The Force Awakens"));
        repository.save(new Quote("I'm sorry, I'm not programmed to impersonate a deity.","K-2SO","Rogue One"));
        repository.save(new Quote("General Kenobi. You are a bold one.","General Grievous","Revenge of the Sith"));
        repository.save(new Quote("There is always hope.","Rey","The Last Jedi"));
        repository.save(new Quote("It's a trap!","Admiral Ackbar","Return of the Jedi"));
        repository.save(new Quote("You are not a Jedi yet.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("The Force will be with you, always.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I've got a bad feeling about this.","Various","Various"));
        repository.save(new Quote("Rey, I want you to join me. We can rule together and bring a new order to the galaxy.","Kylo Ren","The Last Jedi"));
        repository.save(new Quote("You're asking me to be rational. That is something I know I cannot do.","Padme Amidala","Attack of the Clones"));
        repository.save(new Quote("Hello, what have we here?","Lando Calrissian","The Empire Strikes Back"));
        repository.save(new Quote("Remember, the Force will be with you always.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I will not be the last Jedi.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("General Hux, I'm giving you a chance to surrender now.","Poe Dameron","The Last Jedi"));
        repository.save(new Quote("Ah, the negotiator. General Kenobi. We've been waiting for you.","Count Dooku","Attack of the Clones"));
        repository.save(new Quote("You were my brother, Anakin. I loved you.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("Everything is proceeding as I have foreseen.","Emperor Palpatine","Return of the Jedi"));
        repository.save(new Quote("I'll never turn to the dark side. You've failed, your highness. I am a Jedi, like my father before me.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("We are what they grow beyond. That is the true burden of all masters.","Yoda","The Last Jedi"));
        repository.save(new Quote("I don't like this. I don't like this at all.","C-3PO","The Empire Strikes Back"));
        repository.save(new Quote("The force is strong with this one.","Darth Vader","A New Hope"));
        repository.save(new Quote("May the Force be with us.","Jyn Erso","Rogue One"));
        repository.save(new Quote("Why does everyone want to go back to Jakku?","Finn","The Force Awakens"));
        repository.save(new Quote("You're not alone.","Rey","The Rise of Skywalker"));
        repository.save(new Quote("It's the ship that made the Kessel Run in less than twelve parsecs.","Han Solo","A New Hope"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("I am one with the Force, and the Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("I love you. I know.","Leia Organa/Han Solo","The Empire Strikes Back"));
        repository.save(new Quote("Hope is not lost today. It is found.","Leia Organa","The Last Jedi"));
        repository.save(new Quote("It's a new day, a new beginning.","Ahsoka Tano","Star Wars Rebels"));
        repository.save(new Quote("The galaxy will never be free from the grasp of the Empire.","Kanan Jarrus","Star Wars Rebels"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("We are the spark that'll light the fire that'll burn the First Order down.","Poe Dameron","The Last Jedi"));
        repository.save(new Quote("It's over, Anakin! I have the high ground!","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("Who's the more foolish: the fool, or the fool who follows him?","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I'm glad you're here to tell us these things. Chewie! Take the Professor in back and plug him into the hyperdrive!","Han Solo","A New Hope"));
        repository.save(new Quote("Rogue One, may the force be with you.","Mon Mothma","Rogue One"));
        repository.save(new Quote("Let go of your hate.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("If there's a bright center to the universe, you're on the planet that it's farthest from.","Luke Skywalker","A New Hope"));
        repository.save(new Quote("Great kid, don't get cocky.","Han Solo","A New Hope"));
        repository.save(new Quote("Search your feelings. You know it to be true.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("The Force is not a power you have. It's not about lifting rocks. It's the energy between all things, a tension, a balance that binds the universe together.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("We are not alone. Good people will fight if we lead them.","Poe Dameron","The Rise of Skywalker"));
        repository.save(new Quote("You know what I've come for.","Darth Vader","Rogue One"));
        repository.save(new Quote("Chewie, we're home.","Han Solo","The Force Awakens"));
        repository.save(new Quote("Strike me down in anger and I'll always be with you, just like your father.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("That's no moon. It's a space station.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Never tell me the odds.","Han Solo","The Empire Strikes Back"));
        repository.save(new Quote("You can't stop change any more than you can stop the suns from setting.","Shmi Skywalker","The Phantom Menace"));
        repository.save(new Quote("Ben, when we first met, you were just a boy. And now I look at you and I see a man.","Han Solo","The Force Awakens"));
        repository.save(new Quote("I am no Jedi.","Ahsoka Tano","Star Wars Rebels"));
        repository.save(new Quote("The rebellion is built on hope.","Jyn Erso","Rogue One"));
        repository.save(new Quote("A Jedi uses the Force for knowledge and defense, never for attack.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("I find your lack of faith disturbing.","Darth Vader","A New Hope"));
        repository.save(new Quote("Let the past die. Kill it, if you have to. It's the only way to become what you were meant to be.","Kylo Ren","The Last Jedi"));
        repository.save(new Quote("The Force will be with you, always.","Luke Skywalker","The Empire Strikes Back"));
        repository.save(new Quote("You are a part of the Rebel Alliance and a traitor! Take her away!","Darth Vader","A New Hope"));
        repository.save(new Quote("I'm one with the Force. The Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("I have brought peace to the Republic. I am more powerful than the Chancellor. I can overthrow him, and together you and I can rule the galaxy.","Mace Windu","Revenge of the Sith"));
        repository.save(new Quote("Your focus determines your reality.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Your destiny lies with me!","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("Never underestimate a droid.","Kanan Jarrus","Star Wars Rebels"));
        repository.save(new Quote("I've got a bad feeling about this.","Various","Various"));
        repository.save(new Quote("There's always a bigger fish.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Jyn, I'll be there for you. Cassian said I had to.","K-2SO","Rogue One"));
        repository.save(new Quote("I'm not afraid.","Rey","The Force Awakens"));
        repository.save(new Quote("We're not done yet.","Finn","The Rise of Skywalker"));
        repository.save(new Quote("We seem to be made to suffer. It's our lot in life.","C-3PO","A New Hope"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("Do. Or do not. There is no try.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Are you an angel?","Anakin Skywalker","The Phantom Menace"));
        repository.save(new Quote("You do have your moments. Not many, but you have them.","Princess Leia","A New Hope"));
        repository.save(new Quote("Who's the more foolish, the fool or the fool who follows him?","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Impressive. Most impressive.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("I will not be the last Jedi.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("It's a trap!","Admiral Ackbar","Return of the Jedi"));
        repository.save(new Quote("I'm Skywalker. I'm here to rescue you.","Luke Skywalker","A New Hope"));
        repository.save(new Quote("Your overconfidence is your weakness.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("Anakin, you're breaking my heart!","Padme Amidala","Revenge of the Sith"));
        repository.save(new Quote("I'm just a simple man trying to make my way in the universe.","Jango Fett","Attack of the Clones"));
        repository.save(new Quote("Once you start down the dark path, forever will it dominate your destiny.","Yoda","Return of the Jedi"));
        repository.save(new Quote("I've waited a long time for this moment, my little green friend.","Emperor Palpatine","Return of the Jedi"));
        repository.save(new Quote("I find your lack of faith disturbing.","Darth Vader","A New Hope"));
        repository.save(new Quote("I sense great fear in you, Skywalker. You have hate. You have anger. But you don't use them.","Count Dooku","Attack of the Clones"));
        repository.save(new Quote("I've got a bad feeling about this.","Various","Various"));
        repository.save(new Quote("The ability to speak does not make you intelligent.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("If you strike me down, I shall become more powerful than you can possibly imagine.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("An object cannot make you good or evil. The temptation of power, forbidden knowledge, even the desire to do good can lead some down that path. But only you can change yourself.","Bendu","Star Wars Rebels"));
        repository.save(new Quote("No one's ever really gone.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("I won't leave you. Not this time.","Ahsoka Tano","Star Wars Rebels"));
        repository.save(new Quote("You were my brother, Anakin. I loved you.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("Hope is like the sun. If you only believe in it when you can see it, you'll never make it through the night.","Leia Organa","The Last Jedi"));
        repository.save(new Quote("I'm one with the Force. The Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("It's the ship that made the Kessel Run in less than twelve parsecs.","Han Solo","A New Hope"));
        repository.save(new Quote("Your focus determines your reality.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Twice the pride, double the fall.","Count Dooku","Revenge of the Sith"));
        repository.save(new Quote("Help me, Obi-Wan Kenobi. You're my only hope.","Leia Organa","A New Hope"));
        repository.save(new Quote("I will do what I must.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("You have failed me for the last time, Admiral.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("Impressive. Every word in that sentence was wrong.","Luke Skywalker","The Last Jedi"));
        repository.save(new Quote("Remember, the Force will be with you always.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("The Force is strong with you. A powerful Sith you will become. Henceforth, you shall be known as Darth...Vader.","Emperor Palpatine","Revenge of the Sith"));
        repository.save(new Quote("Rebellions are built on hope.","Jyn Erso","Rogue One"));
        repository.save(new Quote("I am one with the Force and the Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("This party's over.","Mace Windu","Attack of the Clones"));
        repository.save(new Quote("May the Force be with you.","Various","Various"));
        repository.save(new Quote("There's always a bigger fish.","Qui-Gon Jinn","The Phantom Menace"));
        repository.save(new Quote("Great, kid! Don't get cocky.","Han Solo","A New Hope"));
        repository.save(new Quote("Never tell me the odds.","Han Solo","The Empire Strikes Back"));
        repository.save(new Quote("Your destiny lies along a different path from mine.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("I will not condone a course of action that will lead us to war.","Padme Amidala","Attack of the Clones"));
        repository.save(new Quote("You don't know the power of the Dark Side!","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("If you're not with me, then you're my enemy.","Anakin Skywalker","Revenge of the Sith"));
        repository.save(new Quote("Why, you stuck-up, half-witted, scruffy-looking nerf herder!","Princess Leia","The Empire Strikes Back"));
        repository.save(new Quote("You are unwise to lower your defenses!","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("I have a bad feeling about this.","Various","Various"));
        repository.save(new Quote("I suggest a new strategy, R2: let the Wookiee win.","C-3PO","A New Hope"));
        repository.save(new Quote("I find that answer vague and unconvincing.","K-2SO","Rogue One"));
        repository.save(new Quote("We seem to be made to suffer. It's our lot in life.","C-3PO","A New Hope"));
        repository.save(new Quote("I'm not afraid.","Luke Skywalker","The Empire Strikes Back"));
        repository.save(new Quote("The Force will be with you, always.","Obi-Wan Kenobi","Star Wars Rebels"));
        repository.save(new Quote("He will join us or die, my master.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("If there's a bright center to the universe, you're on the planet that it's farthest from.","Luke Skywalker","A New Hope"));
        repository.save(new Quote("Obi-Wan has taught you well.","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("The garbage will do.","Rey","The Force Awakens"));
        repository.save(new Quote("I am altering the deal. Pray I don't alter it any further.","Darth Vader","The Empire Strikes Back"));
        repository.save(new Quote("I love you. I know.","Han Solo and Leia Organa","The Empire Strikes Back"));
        repository.save(new Quote("I will finish what you started.","Kylo Ren","The Force Awakens"));
        repository.save(new Quote("Every time I walked away from something I wanted to forget, I told myself it was for a cause that I believed in. A cause that was worth it. Without that, we're lost.","Cassian Andor","Rogue One"));
        repository.save(new Quote("You know, no matter how much we fought, I've always hated watching you leave.","Leia Organa","The Last Jedi"));
        repository.save(new Quote("It is the quest for honor that makes one honorable.","Qui-Gon Jinn","The Clone Wars"));
        repository.save(new Quote("There are things that you cannot solve by jumping in an X-wing and blowing something up!","Ezra Bridger","Star Wars Rebels"));
        repository.save(new Quote("Size matters not. Look at me. Judge me by my size, do you?","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("Chewie, we're home.","Han Solo","The Force Awakens"));
        repository.save(new Quote("General Grievous, you're shorter than I expected.","Anakin Skywalker","Revenge of the Sith"));
        repository.save(new Quote("I am no Jedi.","Ahsoka Tano","Star Wars Rebels"));
        repository.save(new Quote("It's a new day, a new beginning.","Ahsoka Tano","Star Wars Rebels"));
        repository.save(new Quote("The Force will be with you, always.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I'm not a hero, Finn. I'm a stormtrooper. Like all of them, I was taken from a family I'll never know. And raised to do one thing: to fight for the First Order.","FN-2187 (Finn)","The Force Awakens"));
        repository.save(new Quote("Rebellions are built on hope.","Jyn Erso","Rogue One"));
        repository.save(new Quote("Let go of your hate.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("I don't like sand. It's coarse and rough and irritating and it gets everywhere.","Anakin Skywalker","Attack of the Clones"));
        repository.save(new Quote("I'm one with the Force. The Force is with me.","Chirrut ÃŽmwe","Rogue One"));
        repository.save(new Quote("If you strike me down, I shall become more powerful than you can possibly imagine.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I never ask that question until after I've done it.","Han Solo","A New Hope"));
        repository.save(new Quote("Do or do not. There is no try.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("You can't stop the change, any more than you can stop the suns from setting.","Shmi Skywalker","The Phantom Menace"));
        repository.save(new Quote("It's treason, then.","Chancellor Palpatine","Revenge of the Sith"));
        repository.save(new Quote("Always in motion is the future.","Yoda","The Empire Strikes Back"));
        repository.save(new Quote("You came in that thing? You're braver than I thought.","Princess Leia","A New Hope"));
        repository.save(new Quote("I sense a great disturbance in the Force.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Into the garbage chute, flyboy!","Princess Leia","A New Hope"));
        repository.save(new Quote("I'll never join you!","Luke Skywalker","The Empire Strikes Back"));
        repository.save(new Quote("You are the Chosen One! It was said that you would destroy the Sith, not join them! Bring balance to the Force, not leave it in darkness!","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("The Force is strong with this one.","Darth Vader","A New Hope"));
        repository.save(new Quote("That's no moon. It's a space station.","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("I'm Luke Skywalker. I'm here to rescue you.","Luke Skywalker","A New Hope"));
        repository.save(new Quote("Why do I get the feeling you're going to be the death of me?","Obi-Wan Kenobi","Attack of the Clones"));
        repository.save(new Quote("It's a trap!","Admiral Ackbar","Return of the Jedi"));
        repository.save(new Quote("You are unwise to lower your defenses!","Darth Vader","Return of the Jedi"));
        repository.save(new Quote("I find your lack of faith disturbing.","Darth Vader","A New Hope"));
        repository.save(new Quote("Who's the more foolish, the fool or the fool who follows him?","Obi-Wan Kenobi","A New Hope"));
        repository.save(new Quote("Aren't you a little short for a stormtrooper?","Princess Leia","A New Hope"));
        repository.save(new Quote("You were my brother, Anakin! I loved you!","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("May the Force be with us.","General Merrick","Rogue One"));
        repository.save(new Quote("I'm a Jedi, like my father before me.","Luke Skywalker","Return of the Jedi"));
        repository.save(new Quote("We have hope. Rebellions are built on hope.","Jyn Erso","Rogue One"));
        repository.save(new Quote("Hello there.","Obi-Wan Kenobi","Revenge of the Sith"));
        repository.save(new Quote("General Kenobi. You are a bold one.","General Grievous","Revenge of the Sith"));
        repository.save(new Quote("I have brought peace to the galaxy, and for this I will always be remembered.","C-3PO","The Phantom Menace"));
        repository.save(new Quote("You underestimate my power!","Anakin Skywalker","Revenge of the Sith"));
        repository.save(new Quote("If you are not with me, then you are my enemy.","Anakin Skywalker","Revenge of the Sith"));

    }
}
